"Reality Gaming - Follow us on facebook and share the love - https://www.facebook.com/oprealgaming",
"Reality Gaming - Always RSVP or post an LOA for official RG event.",
"Reality Gaming - Woody Allen / Veged: 'Every time I listen to Wagner, I get the urge to invade Poland'",
"Reality Gaming – TAE: ‘by the end of the day i want us to leave that city in flames’",
"Reality Gaming - Hehehehe... I mean goddamn it! - TAE after seeing a Gambler squad drive over an IED ",
"Reality Gaming - Random Watching Anto his stream: 'What do you do for a living' – Anto: 'As little as possible as often as possible'",
"Reality Gaming - Dozer: Oh no, FUCK fuck fuck  (after just ejected by accident from helicopter)",
"Reality Gaming - 'The battlefield was littered with LG corpses' - Andrews after RG's first win on End Game",
"Reality Gaming - Veged: 'Helios == Bulletgod'",
"Reality Gaming - 'They dry-humped us...' - Reasoner, the Team and Community Leader for Liberated Gaming right after being blitzkrieg-ed by RG in the second round",
"Reality Gaming - Helios: 'Cutlass how many are you?' - Veged: 'We have six' - Helios adding 3 members to Cutlass: 'Now you have nine' - Veged: 'No, Nin3 left like half an hour ago'",
"Reality Gaming - Doolz to Gambler medic: 'Do you have any peppa pig plasters?'",
"Reality Gaming - Veged: 'Cutlass only dies to explosions if we can take at least one gambler medic with us. It's true, google it!'",
"Reality Gaming - Zepplin (Over Radio): 'Greeny if you just pull the Challenger forward and then right a bit..' - Greeny: (Open Hatch, Local) 'DON'T TELL ME HOW TO FUCKING DRIVE ZEPPLIN'. - Highroller and PCO laughing like crazy :)",
"Reality Gaming - Caesar: This is why you send Cutlass to do the job... They go in jumping over walls, strafing bunkers,... No fucking fear!  ",
"Reality Gaming - Doolz: 'Your crotch isn't interactable... Is it a faulty crotch?'",
"Reality Gaming - Seal Team Cutlass FTW!",
"Reality Gaming - Blade messing about with chairs pulling them away from people trying to sit on them. Villhelm casually walking by: 'Welcome to second grade school guys.'",
"Reality Gaming - Andrews: 'Evening Everyone and Welcome to Reality Gaming Stimulations Sunday Operation, I mean Simulations",
"Reality Gaming - Nelson: 'Helios is like the nicest guy ever'. Oliver: 'Yeah I'd let him fuck my bitch.'",
"Reality Gaming - Anto: 'There is defiantly someone down in the town taking and receiving...'",
"Reality Gaming - Doolz - 'Jonas, I'm going to rename you corporal hindsight'",
"Reality Gaming - Mars about TAE swimming with Stabcon across a river during heavy firefight: 'Are they trying to retake the town by themselves or did they leave a picture of their mum there?' ",
"Reality Gaming - Stal20048: 'Be advised, I cant see shit from up here!'",
"Reality Gaming - Anto: 'Big whirl-y thing up ahead. Rockets. Many bad. Watch out.'",
"Reality Gaming - Stab: 'Cutlass Bring your Land Rover Overoveroveroveroverover'",
"Reality Gaming - Kimbo: 'For all we know, they could be taking a skydiving course, and we just lit them the fuck up'",
"Reality Gaming - Daveo1996: 'Gambler, Dussack, it seems one enemy has surrendered to our North' - TAE: 'Dussack, Gambler, we don't accept surrender' ",
"Reality Gaming - Oryou : 'The sun is pretty sunny'",
"Reality Gaming - Zepplin: 'oh my god that landing gave me a hard-on'",
"Reality Gaming - Helios: 'They're trying to keep the high-ground' - Stabcon: 'Yeah, but it's not working out for them'. - TAE: 'This isn't Star Wars!'",
"Reality Gaming - Obi - 'You can lie to us, but you can't lie to the Nimitz'",
"Reality Gaming - Daveo: 'You guys cheated or what?' - TAE: 'No, it was DOG squad'",
"Reality Gaming - Stabcon: 'Who is the driver?' - Brooks: 'That would be me.' - Stabcon: 'Nice ass!'",
"Reality Gaming - 'BRRRRRRRRRTTTTTTTTTTTTTTTTTTTTT' - The A-10 as Obi was screaming 'WAVE THE A-10......off...Nevermind.'",
"Reality Gaming - Greeny1911: 'Yesterday I paid for a cocktail with my apple watch. Think I may have reached a whole new level of Arsehole'",
"Reality Gaming - TAE: 'Helios built the mission, he knows what he's doing. I hope.'",
"Reality Gaming - P3te: 'Excuse me, beard coming through!'",
"Reality Gaming - Dozer about suppression: 'I like to use short 50 round bursts.'",
"Reality Gaming - Nelson: 'If I had a framerate this great during all sunday ops, I'd cry with joy.' - Steve Cake: 'I wish I could cry.'"