"Reality Gaming - Did you know, a group of frogs is called an army",
"Reality Gaming - Did you know, a group of owls is called a parliament",
"Reality Gaming - Did you know, you burn more calories sleeping than watching TV",
"Reality Gaming - Did you know, a duck can't walk without bobbing its head",
"Reality Gaming - Did you know, in a deck of cards the king of hearts is the only king without a moustache",
"Reality Gaming - Did you know, its physically impossible for pigs to look up at the sky",
"Reality Gaming - Did you know, a 'jiffy' is an actual unit of time: 1/100th of a second",
"Reality Gaming - Did you know, it is physically impossible for you to lick your own elbow",
"Reality Gaming - Did you know, in England, the Speaker of the House is not allowed to speak",
"Reality Gaming - Did you know, the electric chair was invented by a dentist",
"Reality Gaming - Did you know, you don't notice your eyes blinking - until now",
"Reality Gaming - Did you know, you don't see your nose - until now",
"Reality Gaming - Did you know, No word in the English language rhymes with month, orange, silver, or purple",
"Reality Gaming - Did you know, The 'sixth sick sheik's sixth sheep's sick' is said to be the toughest tongue twister in the English language.",
"Reality Gaming - Did you know, 'Go', is the shortest complete sentence in the English language.",
"Reality Gaming - Did you know, The word 'testify' is based on the Ancient Roman practice of making men swear on their testicles when making a statement in court.",
"Reality Gaming - Did you know, Americans on average eat 18 acres of pizza every day.",
"Reality Gaming - Did you know, Celery has negative calories! It takes more calories to eat a piece of celery than the celery has in it to begin with.",
"Reality Gaming - Did you know, Wearing headphones for just an hour will increase the bacteria in your ear by 700 times.",
"Reality Gaming - Did you know, grapes explode when you put them in the microwave",
"Reality Gaming - Did you know, its physically impossible for pigs to look up at the sky",
"Reality Gaming - Did you know, tree hugging is forbidden in china",
"Reality Gaming - Did you know, the past tense for the English word 'dare' is 'durst'",
"Reality Gaming - Did you know, 111,111,111 x 111,111,111 = 12,345,678,987,654,321",
"Reality Gaming - Did you know, a piece of paper cannot be folded more than 7 times",
"Reality Gaming - Did you know, In France, it is legal to marry a dead person.",
"Reality Gaming - Did you know, Beetles taste like apples, wasps like pine nuts, and worms like fried bacon.",
"Reality Gaming - Did you know, Peanuts are one of the ingredients in dynamite. ",
"Reality Gaming - Did you know, Over 1,000 birds a year die from smashing into windows. ",
"Reality Gaming - Did you know, You'll eat about 35,000 cookies in your lifetime. ",
"Reality Gaming - Did you know, In Tokyo, they sell toupees for dogs. ",
"Reality Gaming - Did you know, A female ferret will die if it goes into heat and cannot find a mate. ",
"Reality Gaming - Did you know, A toothpick is the object most often choked on by Americans. ",
"Reality Gaming - Did you know, According to Genesis 1:20-22 the chicken came before the egg. ",
"Reality Gaming - Did you know, 23% of employees say they have had sex in the office.",
"Reality Gaming - Did you know, Topless saleswomen are legal in Liverpool, England, but only in tropical fish stores.",
"Reality Gaming - Did you know, A Dutch court ruled that a bank robber could deduct the 2,000 Euros he paid for his pistol from the 6,600 Euros he has to return to the bank he robbed. ",
"Reality Gaming - Did you know, The glue on Israeli postage stamps is certified kosher. ",
"Reality Gaming - Did you know, The Bible has been translated into Klingon. ",
"Reality Gaming - Did you know, Worcestershire sauce is made from dissolved fish",
"Reality Gaming - Did you know, The FDA allows bugs and rodent hair in peanut butter",
"Reality Gaming - Did you know, Peanuts can be used for a component to make Dynamite",
"Reality Gaming - Did you know, The largest item on any menu in the world is the roast camel.",
"Reality Gaming - Did you know, The little hole in the sink that lets the water drain out, instead of flowing over the side, is called a 'porcelator'.",
"Reality Gaming - Did you know, 20% of Americans think that the sun orbits around the Earth. ",
"Reality Gaming - Did you know, A party boat filled with 60 men and women capsized in Texas after all the passengers rushed to one side as the boat passed a nude beach. ",
"Reality Gaming - Did you know, Each year, more people are killed by teddy bears than by grizzly bears. ",
"Reality Gaming - Did you know, The average chocolate bar has 8 insect legs in it. ",
"Reality Gaming - Did you know, The world's youngest parents were 8 and 9 and lived in China in 1910. ",
"Reality Gaming - Did you know, The bushes and clouds in Super Mario Bros are exactly the same thing, just painted different colors?",
"Reality Gaming - Did you know, Pac-Man was invented by the designer Toru Iwatani while he was eating pizza.",
"Reality Gaming - Did you know, In 1990 game, Golden Axe from SEGA was voiced entirely by prisoners on death row.",
"Reality Gaming - Did you know, The first gaming console to ever ship with an internal memory was the SEGA Saturn and it shipped with about one megabyte of memory.",
"Reality Gaming - Did you know, GoldenEye's famously brilliant multiplayer mode originally contained three Bond actors as playable characters; Sean Connery, Roger Moore and Timothy Dalton.",
"Reality Gaming - Did you know, It's only humanly possible to press a button on a controller 16 times per second. This record was set by Toshuyuki Takahashi, a Japanese gamer.",
"Reality Gaming - Did you know, Violent, pedestrian-squishing racer Carmageddon was only allowed to be released in the UK with zombies instead of people roaming the streets. In the Indian version, the cows were removed, and it was banned altogether in Germany.",
"Reality Gaming - Did you know, Rockstar Games paid to receive negative press for Grand Theft Auto.",
"Reality Gaming - Did you know, Studies have found that surgeons, who regularly play video games make 37% fewer errors and perform tasks 27% faster than their peers",
"Reality Gaming - Did you know, It is illegal for kids 16 and under in South Korea to play video games past midnight",
"Reality Gaming - Did you know, Obama paid for in-game advertising in Burnout Paradise during his campaign.",
"Reality Gaming - Did you know, Programs in the past versions of Windows Office often contained substantial Easter eggs. Excel 97 contained a reasonably functional flight-simulator.",
"Reality Gaming - Did you know, Chinese prisoners are forced to farm World of Warcraft gold. There are thought to be 100,000 full-time gold farmers in China.",
"Reality Gaming - Did you know, A Chinese man hired multiple cyber-assassins to kill his son’s WoW avatar",
"Reality Gaming - Did you know, There is a hiding spot in Pac-man where you can sit still safely for as long as you like.",
"Reality Gaming - Did you know, The 256th level of Pac-Man is unplayable because of a software bug.",
"Reality Gaming - Did you know, Nearly 37% of purchased Steam games are never played.",
"Reality Gaming - Did you know, Valve originally approached Microsoft and other companies to create a game client with features like auto-updating and a better anti-cheat system, but were refused. So Valve developed it themselves and made Steam."